PersonalWeb/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
import xadmin
from django.views.static import serve
from .settings import MEDIA_ROOT
from django.views.generic.base import RedirectView


urlpatterns = [
    path(r'xadmin', xadmin.site.urls),
    # 使用富文本
    url(r'^ueditor/', include('DjangoUeditor.urls')),
    # 使用blog
    path(r'blog', include('blogs.urls', namespace="blog")),
    # 使用blog
    path(r'', include('storage.urls', namespace="homepage")),
    # 显示图片
    url(r'^media/(?P<path>.*)$',serve,{"document_root":MEDIA_ROOT},name='media'),
    # 配置富文本显示图片路径
    # url(r'^blog/(?P<path>.*)$', ),
    url(r'^favicon\.ioc$', RedirectView.as_view(url=r'static/img/icons/favicon.ico')),
]

blogs/urls.py
from django.conf.urls import url
from .views import BlogListView, BlogContentView, ContactView

app_name = 'blog'

urlpatterns = [
    url(r'list', BlogListView.as_view(), name='blog'),
    url(r'content/(?P<blog_id>\d+)/$', BlogContentView.as_view(), name='content'),
    url(r'contact', ContactView.as_view(), name='contact'),
]

blogs/models.py
from django.db import models
from datetime import datetime
# from DjangoUeditor.models import UEditorField
from DjangoUeditor.models import UEditorField
# Create your models here.


class Blogs(models.Model):
    title = models.CharField(max_length=30, verbose_name="标题")
    blog_mondel = models.ForeignKey('Categorys', verbose_name="博客类别", null=True, blank=True, default='', on_delete=models.SET_NULL)
    lable = models.ManyToManyField('Labels')
    content = UEditorField(verbose_name="文章内容", width=600, height=700, imagePath="blog/images/",
                          filePath="blog/files/", default='')
    add_time = models.DateTimeField(default=datetime.now(), verbose_name="添加时间")
    click_num = models.IntegerField(default=0, verbose_name="点赞量")
    class Meta:
        verbose_name = "博客"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Labels(models.Model):
    lable = models.CharField(max_length=7, verbose_name='标签名称')
    blog_lables = models.ManyToManyField('Blogs', verbose_name='博客')

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.lable


class Categorys(models.Model):
    mondel = models.CharField(max_length=20, verbose_name='博客类别', default='')

    class Meta:
        verbose_name = "类别"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.mondel


class Contact(models.Model):
    pen_name = models.CharField(max_length=15, verbose_name="笔名", default="无名")
    email = models.EmailField(verbose_name="邮箱")
    conten = models.TextField(max_length=500, verbose_name="内容")

    class Meta:
        verbose_name = "联系"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.pen_name

xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/about.html
{% extends 'base.html' %}
{% block title %}
页面旅行去了
{% endblock %}
{% block Navigation %}
            <!-- Breadcrumb area start -->
            <div class="breadcrumb-style-two gray-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="breadcrumb-content">
                                <h2 class="page-cat">about</h2>
                                <ul class="breadcrumb-list">
                                    <li><a href="/">Home</a></li>
                                    <li>about</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
            <!-- Breadcrumb area end -->
{% endblock %}
{% block content %}
            <!-- Theme standard row Start for Buttons -->
            <div class="erika-standard-row">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="area-heading area-heading-style-two text-center">
                                <!--<h2 class="area-title">faq Accordion</h2>-->
                                <p>This is a long road that cannot be turned back. Maybe the sun will never rise again tomorrow. However, the abyss gives us the eyes of hatred. I will use it to see through the end of darkness.</p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="faq-content-wrapper">
                                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="false">
                                    <div class="panel panel-default">
                                        <div class="panel-heading" role="tab" id="headingOne">
                                            <h4 class="panel-title">
                                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">网站简介：</a>
                                          </h4>
                                        </div>
                                        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                                            <div class="panel-body">
                                                <p>本网站属于个人网站，会分享一些实用工具与一些骚操作等等，本人属于python程序员，爱好python，爱好编程，更爱生活的点点滴滴，会一些数据挖掘，数据分析，人工智障等，欢迎交流，多多指点，我会努力完善...</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel panel-default">
                                        <div class="panel-heading" role="tab" id="headingTwo">
                                            <h4 class="panel-title">
                                            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">联系方式</a>
                                          </h4>
                                        </div>
                                        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                                            <div class="panel-body">
                                                <p>QQ:3411894994</p>
                                                <p>WX:ldh15087767923</p>
                                            </div>
                                        </div>
                                    </div>
                                    <!--<div class="panel panel-default">-->
                                        <!--<div class="panel-heading" role="tab" id="headingThree">-->
                                            <!--<h4 class="panel-title">-->
                                            <!--<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">Can I use trademarked names in my items?</a>-->
                                          <!--</h4>-->
                                        <!--</div>-->
                                        <!--<div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">-->
                                            <!--<div class="panel-body">-->
                                                <!--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit neque libero ullam et veniam explicabo vero assumenda cum. Labore, quisquam!</p>-->
                                            <!--</div>-->
                                        <!--</div>-->
                                    <!--</div>-->
                                    <!--<div class="panel panel-default">-->
                                        <!--<div class="panel-heading" role="tab" id="headingFive">-->
                                            <!--<h4 class="panel-title">-->
                                            <!--<a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#follapesFive" aria-expanded="false" aria-controls="follapesFive">How can I get support for an item?</a>-->
                                          <!--</h4>-->
                                        <!--</div>-->
                                        <!--<div id="follapesFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">-->
                                            <!--<div class="panel-body">-->
                                                <!--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Impedit neque libero ullam et veniam explicabo vero assumenda cum. Labore, quisquam!</p>-->
                                            <!--</div>-->
                                        <!--</div>-->
                                    <!--</div>-->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Theme Standard row for buttons end -->
            <!-- Erika Newsletter area start -->
            <!--<div class="erika-standard-row erika-newsletter-area gray-bg">-->
                <!--<div class="container">-->
                    <!--<div class="row">-->
                        <!--<div class="col-xs-12">-->
                            <!--<div class="area-heading area-heading-style-two text-center">-->
                                <!--<h2 class="area-title">subscribe to get in touch</h2>-->
                                <!--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi tempora veritatis nemo aut ea iusto eos est expedita, quas ab adipisci.</p>-->
                            <!--</div>-->
                        <!--</div>-->
                    <!--</div>-->
                    <!--<div class="row">-->
                        <!--<div class="col-md-12 col-sm-12">-->
                            <!--<div class="erika-news-letter text-center">-->
                                <!--<form action="#">-->
                                    <!--<input type="email" placeholder="Email address...">-->
                                    <!--<button type="submit">subscribe</button>-->
                                <!--</form>-->
                            <!--</div>-->
                        <!--</div>-->
                    <!--</div>-->
                <!--</div>-->
            <!--</div>-->
            <!-- Erika Newsletter area End -->
        </div>
        <!-- Main content end -->
    {% endblock %}
    {% block js %}
<script>

</script>
    {% endblock %}

templates/blog-list.html
{% extends 'base.html' %}
{% block title %}
博客列表
{% endblock %}
{% block Navigation %}
            <!-- Breadcrumb area start -->
            <div class="breadcrumb-style-two gray-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="breadcrumb-content">
                                <h2 class="page-cat">Blog Left Sidebar</h2>
                                <ul class="breadcrumb-list">
                                    <li><a href="/">Home</a></li>
                                    <li>blog-list</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Breadcrumb area end -->
{% endblock %}
{% block content %}
            <!-- Theme standard row start for blog -->
            <div class="erika-standard-row white-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-9 col-lg-push-3 col-md-8 col-md-push-4 col-sm-12">
                            <div class="row">
                                <div class="blog-masonry">
                                {% for blog in all_blog.object_list  %}
                                    <div class="col-md-6 col-sm-6 post-grid-item">
                                        <article class="blog-post">
                                            <div class="post-thumbnail">
                                                <a href="#"><img src="{{ blog.img }}" alt=""></a>
                                                <ul class="meta-info">
                                                    <li><a href="#">{{ blog.add_time}}</a></li>
                                                </ul>
                                            </div>
                                            <div class="post-content">
                                                <div class="post-content-inner">
                                                    <h3><a href="#">{{ blog.title }}</a></h3>
                                                    <p>{{ blog.start_content }}</p>
                                                </div>
                                                <div class="post-footer-meta clearfix">
                                                    <ul class="post-action-btn">
                                                        <li><a href="#"><i class="icon-refresh"></i></a></li>
                                                        <li><a href="#"><i class="icon-chat"></i></a></li>
                                                        <li><a href="#"><i class="icon-heart"></i></a></li>
                                                    </ul>
                                                    <div class="read-more-wrapper">
                                                        <a href="/blog/content/{{ blog.id }}" class="read-more">查看更多</a>
                                                        <a href="#" class="like-count"><i class="ti-heart"></i><span>{{ blog.click_num }}</span></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </article>
                                    </div>
                                {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-lg-pull-9 col-md-4 col-md-pull-8 col-sm-12">
                            <!--<aside class="single-widget">-->
                                <!--<h4 class="widget-title">搜索</h4>-->
                                <!--<div class="search-widget">-->
                                    <!--<div>-->
                                        <!--<input type="text" id="search" placeholder="python">-->
                                        <!--<p id="search_form"><i class="ti-search"></i></p>-->
                                    <!--</div>-->
                                <!--</div>-->
                            <!--</aside>-->
                            <aside class="single-widget">
                                <h4 class="widget-title">标签</h4>
                                <div class="tags">
                                    {% for lable in lable_list %}
                                        <a href="?lable={{ lable.id }}">{{ lable.lable }}</a>
                                    {% endfor %}
                                </div>
                            </aside>
                            <aside class="single-widget">
                                <h4 class="widget-title">博客类别</h4>
                                <ul class="post-cat-list">
                                    {% for categorys in categorys_list %}
                                    <li><a href="?categorys={{ categorys.id }}">{{ categorys.mondel }}</a></li>
                                    {% endfor %}
                                </ul>
                            </aside>
                            <aside class="single-widget">
                                <h4 class="widget-title">最近的帖子</h4>
                                <div class="resent-post-widget">
                                    {% for blog_list in blogs_ranking_list %}
                                        <div class="widget-single-post clearfix">
                                            <a href="#"><img style="height: 100px;width: 170px;" src="{{ blog_list.img }}" alt=""></a>
                                            <div class="widget-post-content">
                                                <h4><a href="/blog/content/{{ blog_list.id }}" >{{ blog_list.title }}</a></h4>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </aside>
                        </div>

                    </div>
                        <div class="row">
                          <div class="col-md-12">
                              <div class="text-center erika-pagingtion">
                                  <ul class="pagination">
                                  {% if all_blog.has_previous %}
                                      <li><a href="?{{ all_blog.previous_page_number.querystring }}" class="prev">上一页</a></li>
                                  {% endif %}

                                  {% for page in all_blog.pages %}
                                    {% if page %}
                                        {% ifequal page all_blog.number %}
                                            <li class="disabled"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                        {% else %}
                                            <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                        {% endifequal %}
                                    {% else %}
                                        <li class="none"><a href="">...</a></li>
                                    {% endif %}
                                  {% endfor %}
                                {% if all_blog.has_next %}
                                  <li class="long"><a href="?{{ all_blog.next_page_number.querystring }}">下一页</a></li>
                                {% endif %}
                                  </ul>
                              </div>
                          </div>

                      </div>
                  </div>


                </div>
            </div>
            <!-- Theme standard row end for blog -->
        </div>
        <!-- Main content end -->
        <!-- Footer area end -->
    {% endblock %}
    {% block js %}
<script>

</script>
    {% endblock %}

templates/collection.html
{% extends 'base.html' %}
{% block title %}
博客列表
{% endblock %}
{% block Navigation %}
<!-- Breadcrumb area start -->
<!--<div class="breadcrumb-style-two gray-bg">-->
    <!--<div class="container">-->
        <!--<div class="row">-->
            <!--<div class="col-xs-12">-->
                <!--<div class="breadcrumb-content">-->
                    <!--<h2 class="page-cat">Accordion</h2>-->
                    <!--<ul class="breadcrumb-list">-->
                        <!--<li><a href="index.html">Home</a></li>-->
                        <!--<li>Accordion</li>-->
                    <!--</ul>-->
                <!--</div>-->
            <!--</div>-->
        <!--</div>-->
    <!--</div>-->
<!--</div>-->
<!-- Breadcrumb area end -->
{% endblock %}
{% block content %}
            <!-- Theme standard row Start for Buttons -->
            <div class="erika-standard-row">
                <div class="container">
                    <!--<div class="row">-->
                        <!--<div class="col-xs-12">-->
                            <!--<div class="area-heading area-heading-style-two text-center">-->
                                <!--<h2 class="area-title">faq Accordion</h2>-->
                                <!--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi tempora veritatis nemo aut ea iusto eos est expedita, quas ab adipisci.</p>-->
                            <!--</div>-->
                        <!--</div>-->
                    <!--</div>-->
                    <div class="row">
                        <div class="col-md-12">
                            <div class="faq-content-wrapper">
                                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="false">

                                    <div class="list-group">
                                        {% for storage in storage_all %}
                                        <a href="{{ storage.url_path }}" class="list-group-item">
                                            <h4 class="list-group-item-heading">{{ storage.get_degree_display }}</h4>
                                            <p class="list-group-item-text">{{ storage.explain }}&emsp;&emsp;{{ storage.add_time }}</p>
                                        </a>
                                        {% endfor %}
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Theme Standard row for buttons end -->
    {% endblock %}
    {% block js %}
    {% endblock %}